function [agt_ctnr]=create_agents()

%Sets up agent parameters and
%creates the objects representing each agent
%agt_ctnr: agent container (cell array containing list of objects representing agents)
% ----------------------------------
%Project: AC-Lab by M.G. [created Feb 2020]
%Main Function: aclab_go
% ----------------------------------

global PRMS_ACLAB PRMS_C_LAB PRMS_C_CD PRMS_C_CR MESSAGES 

% -------------------------------------------------------------------
% --- STANDARD MODE INIZIALIZATION ----------------------------------
% -------------------------------------------------------------------
if PRMS_ACLAB.c_mode == PRMS_ACLAB.c_mode_sd %%% IF STANDARD CONFIGURATION 
    %%% --- set initial position [x,y] of agents --------------------
    cd_pos = PRMS_C_CD.pos; %initial child position
    cr_pos = PRMS_C_CR.pos; %initial caregiver position
% -------------------------------------------------------------------
% --- RANDOM MODE INIZIALIZATION ------------------------------------
% -------------------------------------------------------------------
elseif PRMS_ACLAB.c_mode == PRMS_ACLAB.c_mode_rm %%% IF RANDOM CONFIGURATION  
    %%% --- set initial position [x,y] of agents --------------------
    cd_pos = (PRMS_C_LAB.size-1)*rand(PRMS_ACLAB.n_cd,2)+1; %generate random initial positions for children
    cr_pos = (PRMS_C_LAB.size-1)*rand(PRMS_ACLAB.n_cr,2)+1; %generate random initial positions for caregivers
else
    %ERROR MESSAGE
end  
    
% --- generate all child agents -------------------------------------
for cd=1:PRMS_ACLAB.n_cd
    pos = cd_pos(cd,:);
    
    cd_iwm = iwm(PRMS_C_CD.ad2_av,...
                 PRMS_C_CD.ad3_am,...
                 PRMS_C_CD.ad4_ph,...
                 PRMS_C_CD.thrshld4_ad2,...
                 PRMS_C_CD.thrshld4_ad3,...
                 PRMS_C_CD.thrshld4_ad4,...
                 0,...
                 0,...
                 0,...
                 0,...
                 0,...
                 0);
        
    agt_ctnr{cd} = child(pos,...
                         PRMS_C_CD.speed,...
                         PRMS_C_CD.ex_range,...
                         cd_iwm,...
                         PRMS_C_CD.need4_cf2,...
                         PRMS_C_CD.need4_cf3,...
                         PRMS_C_CD.need4_cf4,...
                         PRMS_C_CD.p2need_cf2_x,...
                         PRMS_C_CD.p2need_cf3_x,...
                         PRMS_C_CD.p2need_cf4_x,...
                         PRMS_C_CD.p2need_cf2_xf,...
                         PRMS_C_CD.p2need_cf3_xf,...
                         PRMS_C_CD.p2need_cf4_xf,...
                         PRMS_C_CD.p2need_cf2,...
                         PRMS_C_CD.p2need_cf3,...
                         PRMS_C_CD.p2need_cf4,...
                         PRMS_C_CD.no_cf2_cntr,...
                         PRMS_C_CD.no_cf3_cntr,...
                         PRMS_C_CD.no_cf4_cntr,...
                         PRMS_C_CD.cf2_ed,...
                         PRMS_C_CD.cf3_pd,... 
                         PRMS_C_CD.cf4_vu,... 
                         PRMS_C_CD.cf2_ed_trgt,...
                         PRMS_C_CD.cf3_pd_trgt,...
                         PRMS_C_CD.cf4_vu_trgt,...
                         PRMS_C_CD.cf2_i,...
                         PRMS_C_CD.cf3_d,...
                         PRMS_C_CD.cf4_d,...
                         PRMS_C_CD.cf2_i_trgt,...
                         PRMS_C_CD.cf3_d_trgt,...
                         PRMS_C_CD.cf4_d_trgt,...
                         PRMS_C_CD.cf2_if,...
                         PRMS_C_CD.cf3_df,...
                         PRMS_C_CD.cf4_df);                   
end
% --- generate all caregiver agents ---------------------------------
for cr=PRMS_ACLAB.n_cd+1:PRMS_ACLAB.n_cd+PRMS_ACLAB.n_cr
    pos = cr_pos(cr-PRMS_ACLAB.n_cd,:);
    
    cr_iwm = iwm(0,...
                 0,...
                 0,...
                 0,...
                 0,...
                 0,...
                 PRMS_C_CR.cf2_in,...
                 PRMS_C_CR.cf3_un,...
                 PRMS_C_CR.cf4_li,...
                 PRMS_C_CR.thrshld4_cf2,...
                 PRMS_C_CR.thrshld4_cf3,...
                 PRMS_C_CR.thrshld4_cf4);
        
    agt_ctnr{cr} = caregiver(pos,...
                             PRMS_C_CR.speed,...
                             PRMS_C_CR.ex_range,...
                             cr_iwm,...
                             PRMS_C_CR.need2give_cf2,...
                             PRMS_C_CR.need2give_cf3,...
                             PRMS_C_CR.need2give_cf4,...
                             PRMS_C_CR.p2give_cf2_x,...
                             PRMS_C_CR.p2give_cf3_x,...
                             PRMS_C_CR.p2give_cf4_x,...
                             PRMS_C_CR.p2give_cf2_xf,...
                             PRMS_C_CR.p2give_cf3_xf,...
                             PRMS_C_CR.p2give_cf4_xf,...
                             PRMS_C_CR.p2give_cf2,...
                             PRMS_C_CR.p2give_cf3,...
                             PRMS_C_CR.p2give_cf4,...
                             PRMS_C_CR.no_cf2_cntr,...
                             PRMS_C_CR.no_cf3_cntr,...
                             PRMS_C_CR.no_cf4_cntr,...
                             PRMS_C_CR.cf2_ed,...
                             PRMS_C_CR.cf3_pd,...
                             PRMS_C_CR.cf4_vu,...
                             PRMS_C_CR.cf2_ed_trgt,...
                             PRMS_C_CR.cf3_pd_trgt,...
                             PRMS_C_CR.cf4_vu_trgt,...
                             PRMS_C_CR.cf2_i,...
                             PRMS_C_CR.cf3_d,...
                             PRMS_C_CR.cf4_d,...
                             PRMS_C_CR.cf2_i_trgt,...
                             PRMS_C_CR.cf3_d_trgt,...
                             PRMS_C_CR.cf4_d_trgt,...
                             PRMS_C_CR.cf2_if,...
                             PRMS_C_CR.cf3_df,...
                             PRMS_C_CR.cf4_df);
end

%%% --- set initial position [x,y] of agents ------------------------

MESSAGES.pos=[cd_pos;cr_pos];


