 
% ----------------------------------
%Project: AC-Lab by M.G. [created Feb 2020]
%Main Function: aclab_go
% ----------------------------------

%- plot variables ---------------------
% x: dimensional levels 0.1 - 0.9
% y_01: 
% y_02: 
% y_03: Lab Distance
% y_04: 
% y_05: CD need4
% y_06: CR need2give
% y_07: It.s with no cf
% y_08: CD x-distance/vulnerability
% y_09: CR x-distance/vulnerability
% y_10: CD x-distance/vulnerability target
% y_11: CR x-distance/vulnerability target
% y_12: CD indifference/distancing
% y_13: CR indifference/distancing
% y_14: CD indifference/distancing target
% y_15: CR indifference/distancing target
% y_16: CD Exploring
% y_17: CD Approaching
% y_18: CR Exploring
% y_19: CR Approaching
%--------------------------------------

%- line function y = mx + q defined below

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% SETTING for Normal %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% - avoidance line ---
av_cd_n_m  = -100+10; % avoidance child     need m         OK Result_vs_Target_Normal
av_cr_n_m  = -100+10; % avoidance caregiver need m         OK Result_vs_Target_Normal
av_cd_ap_m = -100+15; % avoidance child     approach m     OK Result_vs_Target_Normal
av_cr_ap_m = -100+15; % avoidance caregiver approach m     OK Result_vs_Target_Normal
av_cd_ex_m = +100;    % avoidance child     exploration m  OK Result_vs_Target_Normal
av_cr_ex_m = +100;    % avoidance caregiver exploration m  OK Result_vs_Target_Normal
av_cd_d_m  = +100;    % avoidance child     lab distance m
av_cr_d_m  = +100;    % avoidance caregiver lab distance m

av_cd_n_q  = +100-27; % avoidance child     need q         OK Result_vs_Target_Normal     
av_cr_n_q  = +100-27; % avoidance caregiver need q         OK Result_vs_Target_Normal
av_cd_ap_q = +100-45; % avoidance child     approach q     OK Result_vs_Target_Normal
av_cr_ap_q = +100-45; % avoidance caregiver approach q     OK Result_vs_Target_Normal
av_cd_ex_q = +0+5;    % avoidance child     exploration q  OK Result_vs_Target_Normal
av_cr_ex_q = +0+5;    % avoidance caregiver exploration q  OK Result_vs_Target_Normal
av_cd_d_q  = +100;    % avoidance child     lab distance q
av_cr_d_q  = +100;    % avoidance caregiver lab distance q

% - ambivalence line ---
am_cd_n_m  = +100+80; % ambivalence child     need m         OK Result_vs_Target_Normal
am_cr_n_m  = -100;    % ambivalence caregiver need m         OK Result_vs_Target_Normal
am_cd_ap_m = +100+35; % ambivalence child     approach m     OK Result_vs_Target_Normal
am_cr_ap_m = -100+20; % ambivalence caregiver approach m     OK Result_vs_Target_Normal
am_cd_ex_m = -100-30; % ambivalence child     exploration m  OK Result_vs_Target_Normal
am_cr_ex_m = +100+10; % ambivalence caregiver exploration m  OK Result_vs_Target_Normal
am_cd_d_m  = -100;    % ambivalence child     lab distance m
am_cr_d_m  = +100;    % ambivalence caregiver lab distance m

am_cd_n_q  = +0-30;   % ambivalence child     need q         OK Result_vs_Target_Normal
am_cr_n_q  = +100-30; % ambivalence caregiver need q         OK Result_vs_Target_Normal
am_cd_ap_q = +0-45;   % ambivalence child     approach q     OK Result_vs_Target_Normal
am_cr_ap_q = +100-45; % ambivalence caregiver approach q     OK Result_vs_Target_Normal
am_cd_ex_q = +100+0;  % ambivalence child     exploration q  OK Result_vs_Target_Normal
am_cr_ex_q = +0-0;    % ambivalence caregiver exploration q  OK Result_vs_Target_Normal
am_cd_d_q  = +100;    % ambivalence child     lab distance q
am_cr_d_q  = +100;    % ambivalence caregiver lab distance q

% - phobicity line ---
ph_cd_n_m =  +100-25; % phobicity child     need m           OK Result_vs_Target_Normal
ph_cr_n_m =  +100-25; % phobicity caregiver need m           OK Result_vs_Target_Normal
ph_cd_ap_m = +100;    % phobicity child     approach m
ph_cr_ap_m = +100;    % phobicity caregiver approach m
ph_cd_ex_m = -100;    % phobicity child     exploration m
ph_cr_ex_m = -100;    % phobicity caregiver exploration m
ph_cd_d_m  = -24;     % phobicity child     lab distance m OK Result_vs_Target_Normal
ph_cr_d_m  = -24;     % phobicity caregiver lab distance m OK Result_vs_Target_Normal
%ph_cd_d_m  = -24;     % phobicity child     lab distance m Actual Targets
%ph_cr_d_m  = -24;     % phobicity caregiver lab distance m Actual Targets

ph_cd_n_q =  +0+5;    % phobicity child     need q         OK Result_vs_Target_Normal
ph_cr_n_q =  +0+5;    % phobicity caregiver need q         OK Result_vs_Target_Normal
ph_cd_ap_q = +0;      % phobicity child     approach q
ph_cr_ap_q = +0;      % phobicity caregiver approach q
ph_cd_ex_q = +100;    % phobicity child     exploration q
ph_cr_ex_q = +100;    % phobicity caregiver exploration q
ph_cd_d_q  = +26;     % phobicity child     lab distance q OK Result_vs_Target_Normal
ph_cr_d_q  = +26;     % phobicity caregiver lab distance q OK Result_vs_Target_Normal
%ph_cd_d_q  = +24;     % phobicity child     lab distance q Actual Targets
%ph_cr_d_q  = +24;     % phobicity caregiver lab distance q Actual Targets

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% SETTING for Dynamics %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% % - avoidance line ---
% av_cd_n_m  = -100+35; % avoidance child     need m         OK Result_vs_Target_Dynamics
% av_cr_n_m  = -100+25; % avoidance caregiver need m         OK Result_vs_Target_Dynamics
% av_cd_ap_m = -100+10; % avoidance child     approach m     OK Result_vs_Target_Dynamics
% av_cr_ap_m = -100+15; % avoidance caregiver approach m     OK Result_vs_Target_Dynamics
% av_cd_ex_m = +100;    % avoidance child     exploration m  OK Result_vs_Target_Dynamics
% av_cr_ex_m = +100;    % avoidance caregiver exploration m  OK Result_vs_Target_Dynamics
% av_cd_d_m  = +100;    % avoidance child     lab distance m
% av_cr_d_m  = +100;    % avoidance caregiver lab distance m
% 
% av_cd_n_q  = +100-34; % avoidance child     need q         OK Result_vs_Target_Dynamics   
% av_cr_n_q  = +100-26; % avoidance caregiver need q         OK Result_vs_Target_Dynamics
% av_cd_ap_q = +100-45; % avoidance child     approach q     OK Result_vs_Target_Dynamics
% av_cr_ap_q = +100-45; % avoidance caregiver approach q     OK Result_vs_Target_Dynamics
% av_cd_ex_q = +0+7;    % avoidance child     exploration q  OK Result_vs_Target_Dynamics
% av_cr_ex_q = +0+5;    % avoidance caregiver exploration q  OK Result_vs_Target_Dynamics
% av_cd_d_q  = +100;    % avoidance child     lab distance q
% av_cr_d_q  = +100;    % avoidance caregiver lab distance q
% 
% % - ambivalence line ---
% am_cd_n_m  = +100+70; % ambivalence child     need m         OK Result_vs_Target_Dynamics
% am_cr_n_m  = -100+10; % ambivalence caregiver need m         OK Result_vs_Target_Dynamics
% am_cd_ap_m = +100+35; % ambivalence child     approach m     OK Result_vs_Target_Dynamics
% am_cr_ap_m = -100+20; % ambivalence caregiver approach m     OK Result_vs_Target_Dynamics
% am_cd_ex_m = -100-30; % ambivalence child     exploration m  OK Result_vs_Target_Dynamics
% am_cr_ex_m = +100+10; % ambivalence caregiver exploration m  OK Result_vs_Target_Dynamics
% am_cd_d_m  = -100;    % ambivalence child     lab distance m
% am_cr_d_m  = +100;    % ambivalence caregiver lab distance m
% 
% am_cd_n_q  = +0-30;   % ambivalence child     need q         OK Result_vs_Target_Dynamics
% am_cr_n_q  = +100-30; % ambivalence caregiver need q         OK Result_vs_Target_Dynamics
% am_cd_ap_q = +0-45;   % ambivalence child     approach q     OK Result_vs_Target_Dynamics
% am_cr_ap_q = +100-45; % ambivalence caregiver approach q     OK Result_vs_Target_Dynamics
% am_cd_ex_q = +100+0;  % ambivalence child     exploration q  OK Result_vs_Target_Dynamics
% am_cr_ex_q = +0-0;    % ambivalence caregiver exploration q  OK Result_vs_Target_Dynamics
% am_cd_d_q  = +100;    % ambivalence child     lab distance q
% am_cr_d_q  = +100;    % ambivalence caregiver lab distance q

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% GET DATA %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if Av_ON
    dimension = 'Av';
    load('plot_reports_ws_av','x',...
                              'y_av_03',...  % Lab Distance
                              'y_av_05',...  % CD need
                              'y_av_06',...  % CR need
                              'y_av_16',...  % CD Exploring
                              'y_av_17',...  % CD Approaching
                              'y_av_18',...  % CR Exploring
                              'y_av_19');    % CR Approaching
    %load('plot_reports_ws_av');% load all workspace for avoidance
    y_03 = y_av_03;% Lab Distance
    y_05 = y_av_05;% CD need
    y_06 = y_av_06;% CR need
    y_16 = y_av_16;% CD Exploring
    y_17 = y_av_17;% CD Approaching
    y_18 = y_av_18;% CR Exploring
    y_19 = y_av_19;% CR Approaching
    %lines: y = av_cd_n_m * x + av_cd_n_q
    delta = .3;
    N_CD_T = [yf(0.1,av_cd_n_m,av_cd_n_q) ...
              yf(0.2,av_cd_n_m,av_cd_n_q) ...
              yf(0.3,av_cd_n_m,av_cd_n_q) ...
              yf(0.4,av_cd_n_m,av_cd_n_q) ...
              yf(0.5,av_cd_n_m,av_cd_n_q) ...
              yf(0.6,av_cd_n_m,av_cd_n_q) ...
              yf(0.7,av_cd_n_m,av_cd_n_q) ...
              yf(0.8,av_cd_n_m,av_cd_n_q) ...
              yf(0.9,av_cd_n_m,av_cd_n_q)];
    N_CR_T = [yf(0.1,av_cr_n_m,av_cr_n_q) ...
              yf(0.2,av_cr_n_m,av_cr_n_q) ...
              yf(0.3,av_cr_n_m,av_cr_n_q) ...
              yf(0.4,av_cr_n_m,av_cr_n_q) ...
              yf(0.5,av_cr_n_m,av_cr_n_q) ...
              yf(0.6,av_cr_n_m,av_cr_n_q) ...
              yf(0.7,av_cr_n_m,av_cr_n_q) ...
              yf(0.8,av_cr_n_m,av_cr_n_q) ...
              yf(0.9,av_cr_n_m,av_cr_n_q)]+delta;
    Ap_CD_T = [yf(0.1,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.2,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.3,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.4,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.5,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.6,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.7,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.8,av_cd_ap_m,av_cd_ap_q) ...
               yf(0.9,av_cd_ap_m,av_cd_ap_q)];
    Ap_CR_T = [yf(0.1,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.2,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.3,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.4,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.5,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.6,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.7,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.8,av_cr_ap_m,av_cr_ap_q) ...
               yf(0.9,av_cr_ap_m,av_cr_ap_q)]+delta;
    Ex_CD_T = [yf(0.1,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.2,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.3,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.4,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.5,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.6,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.7,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.8,av_cd_ex_m,av_cd_ex_q) ...
               yf(0.9,av_cd_ex_m,av_cd_ex_q)];
    Ex_CR_T = [yf(0.1,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.2,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.3,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.4,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.5,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.6,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.7,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.8,av_cr_ex_m,av_cr_ex_q) ...
               yf(0.9,av_cr_ex_m,av_cr_ex_q)]+delta;
    D_CD_T = [yf(0.1,av_cd_d_m,av_cd_d_q) ...
               yf(0.2,av_cd_d_m,av_cd_d_q) ...
               yf(0.3,av_cd_d_m,av_cd_d_q) ...
               yf(0.4,av_cd_d_m,av_cd_d_q) ...
               yf(0.5,av_cd_d_m,av_cd_d_q) ...
               yf(0.6,av_cd_d_m,av_cd_d_q) ...
               yf(0.7,av_cd_d_m,av_cd_d_q) ...
               yf(0.8,av_cd_d_m,av_cd_d_q) ...
               yf(0.9,av_cd_d_m,av_cd_d_q)];
    D_CR_T = [yf(0.1,av_cr_d_m,av_cr_d_q) ...
               yf(0.2,av_cr_d_m,av_cr_d_q) ...
               yf(0.3,av_cr_d_m,av_cr_d_q) ...
               yf(0.4,av_cr_d_m,av_cr_d_q) ...
               yf(0.5,av_cr_d_m,av_cr_d_q) ...
               yf(0.6,av_cr_d_m,av_cr_d_q) ...
               yf(0.7,av_cr_d_m,av_cr_d_q) ...
               yf(0.8,av_cr_d_m,av_cr_d_q) ...
               yf(0.9,av_cr_d_m,av_cr_d_q)]+delta;
    %base values
    N_CD_T_b = [90 80 70 60 50 40 30 20 10];
    N_CR_T_b = [90 80 70 60 50 40 30 20 10]+delta;
    Ap_CD_T_b = [90 80 70 60 50 40 30 20 10];
    Ap_CR_T_b = [90 80 70 60 50 40 30 20 10]+delta;
    Ex_CD_T_b = [10 20 30 40 50 60 70 80 90];
    Ex_CR_T_b = [10 20 30 40 50 60 70 80 90]+delta;
    D_CD_T_b = [2.4 4.8 7.2 9.6 12 14.4 16.8 19.2 21.6];
    D_CR_T_b = [2.4 4.8 7.2 9.6 12 14.4 16.8 19.2 21.6]+delta;
    CD_T = flip(N_CD_T_b);
    CR_T = flip(N_CR_T_b);   
end

if Am_ON
    dimension = 'Am';
    load('plot_reports_ws_am','x',...
                              'y_am_03',...  % Lab Distance
                              'y_am_05',...  % CD need
                              'y_am_06',...  % CR need
                              'y_am_16',...  % CD Exploring
                              'y_am_17',...  % CD Approaching
                              'y_am_18',...  % CR Exploring
                              'y_am_19');    % CR Approaching
    %load('plot_reports_ws_am');% load all workspace for ambivalence
    y_03 = y_am_03;% Lab Distance
    y_05 = y_am_05;% CD need
    y_06 = y_am_06;% CR need
    y_16 = y_am_16;% CD Exploring
    y_17 = y_am_17;% CD Approaching
    y_18 = y_am_18;% CR Exploring
    y_19 = y_am_19;% CR Approaching
    %lines: y = am_cd_n_m * x + am_cd_n_q
    delta = 0;
    N_CD_T = [yf(0.1,am_cd_n_m,am_cd_n_q) ...
              yf(0.2,am_cd_n_m,am_cd_n_q) ...
              yf(0.3,am_cd_n_m,am_cd_n_q) ...
              yf(0.4,am_cd_n_m,am_cd_n_q) ...
              yf(0.5,am_cd_n_m,am_cd_n_q) ...
              yf(0.6,am_cd_n_m,am_cd_n_q) ...
              yf(0.7,am_cd_n_m,am_cd_n_q) ...
              yf(0.8,am_cd_n_m,am_cd_n_q) ...
              yf(0.9,am_cd_n_m,am_cd_n_q)];
    N_CR_T = [yf(0.1,am_cr_n_m,am_cr_n_q) ...
              yf(0.2,am_cr_n_m,am_cr_n_q) ...
              yf(0.3,am_cr_n_m,am_cr_n_q) ...
              yf(0.4,am_cr_n_m,am_cr_n_q) ...
              yf(0.5,am_cr_n_m,am_cr_n_q) ...
              yf(0.6,am_cr_n_m,am_cr_n_q) ...
              yf(0.7,am_cr_n_m,am_cr_n_q) ...
              yf(0.8,am_cr_n_m,am_cr_n_q) ...
              yf(0.9,am_cr_n_m,am_cr_n_q)]+delta;
    Ap_CD_T = [yf(0.1,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.2,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.3,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.4,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.5,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.6,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.7,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.8,am_cd_ap_m,am_cd_ap_q) ...
               yf(0.9,am_cd_ap_m,am_cd_ap_q)];
    Ap_CR_T = [yf(0.1,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.2,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.3,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.4,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.5,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.6,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.7,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.8,am_cr_ap_m,am_cr_ap_q) ...
               yf(0.9,am_cr_ap_m,am_cr_ap_q)]+delta;
    Ex_CD_T = [yf(0.1,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.2,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.3,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.4,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.5,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.6,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.7,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.8,am_cd_ex_m,am_cd_ex_q) ...
               yf(0.9,am_cd_ex_m,am_cd_ex_q)];
    Ex_CR_T = [yf(0.1,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.2,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.3,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.4,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.5,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.6,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.7,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.8,am_cr_ex_m,am_cr_ex_q) ...
               yf(0.9,am_cr_ex_m,am_cr_ex_q)]+delta;
    D_CD_T = [yf(0.1,am_cd_d_m,am_cd_d_q) ...
               yf(0.2,am_cd_d_m,am_cd_d_q) ...
               yf(0.3,am_cd_d_m,am_cd_d_q) ...
               yf(0.4,am_cd_d_m,am_cd_d_q) ...
               yf(0.5,am_cd_d_m,am_cd_d_q) ...
               yf(0.6,am_cd_d_m,am_cd_d_q) ...
               yf(0.7,am_cd_d_m,am_cd_d_q) ...
               yf(0.8,am_cd_d_m,am_cd_d_q) ...
               yf(0.9,am_cd_d_m,am_cd_d_q)];
    D_CR_T = [yf(0.1,am_cr_d_m,am_cr_d_q) ...
               yf(0.2,am_cr_d_m,am_cr_d_q) ...
               yf(0.3,am_cr_d_m,am_cr_d_q) ...
               yf(0.4,am_cr_d_m,am_cr_d_q) ...
               yf(0.5,am_cr_d_m,am_cr_d_q) ...
               yf(0.6,am_cr_d_m,am_cr_d_q) ...
               yf(0.7,am_cr_d_m,am_cr_d_q) ...
               yf(0.8,am_cr_d_m,am_cr_d_q) ...
               yf(0.9,am_cr_d_m,am_cr_d_q)]+delta;
    %base values
    delta = 0;
    N_CD_T_b = [10 20 30 40 50 60 70 80 90];
    N_CR_T_b = [90 80 70 60 50 40 30 20 10]+delta;
    Ap_CD_T_b = [10 20 30 40 50 60 70 80 90];
    Ap_CR_T_b = [90 80 70 60 50 40 30 20 10]+delta;
    Ex_CD_T_b = [90 80 70 60 50 40 30 20 10];
    Ex_CR_T_b = [10 20 30 40 50 60 70 80 90]+delta;
    D_CD_T_b = [21.6 19.2 16.8 14.4 12 9.6 7.2 4.8 2.4];
    D_CR_T_b = [2.4 4.8 7.2 9.6 12 14.4 16.8 19.2 21.6]+delta;
    CD_T = flip(N_CD_T_b);
    CR_T = flip(N_CR_T_b - delta);   
end

if Ph_ON
    dimension = 'Ph';
    load('plot_reports_ws_ph','x',...
                              'y_ph_03',...  % Lab Distance
                              'y_ph_05',...  % CD need
                              'y_ph_06',...  % CR need
                              'y_ph_16',...  % CD Exploring
                              'y_ph_17',...  % CD Approaching
                              'y_ph_18',...  % CR Exploring
                              'y_ph_19');    % CR Approaching
    %load('plot_reports_ws_ph');% load all workspace for phobicity
    y_03 = y_ph_03;% Lab Distance
    y_05 = y_ph_05;% CD need
    y_06 = y_ph_06;% CR need
    y_16 = y_ph_16;% CD Exploring
    y_17 = y_ph_17;% CD Approaching
    y_18 = y_ph_18;% CR Exploring
    y_19 = y_ph_19;% CR Approaching
    %lines: y = ph_cd_n_m * x + ph_cd_n_q
    delta = .3;
    N_CD_T = [yf(0.1,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.2,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.3,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.4,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.5,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.6,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.7,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.8,ph_cd_n_m,ph_cd_n_q) ...
              yf(0.9,ph_cd_n_m,ph_cd_n_q)];
    N_CR_T = [yf(0.1,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.2,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.3,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.4,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.5,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.6,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.7,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.8,ph_cr_n_m,ph_cr_n_q) ...
              yf(0.9,ph_cr_n_m,ph_cr_n_q)]+delta;
    Ap_CD_T = [yf(0.1,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.2,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.3,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.4,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.5,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.6,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.7,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.8,ph_cd_ap_m,ph_cd_ap_q) ...
               yf(0.9,ph_cd_ap_m,ph_cd_ap_q)];
    Ap_CR_T = [yf(0.1,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.2,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.3,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.4,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.5,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.6,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.7,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.8,ph_cr_ap_m,ph_cr_ap_q) ...
               yf(0.9,ph_cr_ap_m,ph_cr_ap_q)]+delta;
    Ex_CD_T = [yf(0.1,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.2,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.3,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.4,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.5,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.6,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.7,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.8,ph_cd_ex_m,ph_cd_ex_q) ...
               yf(0.9,ph_cd_ex_m,ph_cd_ex_q)];
    Ex_CR_T = [yf(0.1,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.2,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.3,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.4,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.5,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.6,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.7,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.8,ph_cr_ex_m,ph_cr_ex_q) ...
               yf(0.9,ph_cr_ex_m,ph_cr_ex_q)]+delta;
    D_CD_T = [yf(0.1,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.2,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.3,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.4,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.5,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.6,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.7,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.8,ph_cd_d_m,ph_cd_d_q) ...
               yf(0.9,ph_cd_d_m,ph_cd_d_q)];
    D_CR_T = [yf(0.1,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.2,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.3,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.4,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.5,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.6,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.7,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.8,ph_cr_d_m,ph_cr_d_q) ...
               yf(0.9,ph_cr_d_m,ph_cr_d_q)]+delta;
    %base values
    delta = .3;
    N_CD_T_b = [10 20 30 40 50 60 70 80 90];
    N_CR_T_b = [10 20 30 40 50 60 70 80 90]+delta;
    Ap_CD_T_b = [10 20 30 40 50 60 70 80 90];
    Ap_CR_T_b = [10 20 30 40 50 60 70 80 90]+delta;
    Ex_CD_T_b = [90 80 70 60 50 40 30 20 10];
    Ex_CR_T_b = [90 80 70 60 50 40 30 20 10]+delta;
    D_CD_T_b = [21.6 19.2 16.8 14.4 12 9.6 7.2 4.8 2.4];
    D_CR_T_b = [21.6 19.2 16.8 14.4 12 9.6 7.2 4.8 2.4]+delta;
    CD_T = flip(N_CD_T_b);
    CR_T = flip(N_CR_T_b);
end
                             
% --- set up colors -------------------
plot_set_up % m file with colors & positions

%- line function ----------------------
function y=yf(x,m,q)
    y = m*x+q;
end
%--------------------------------------
