%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% --- cf2 plot_stats print on screen ------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ----------------------------------
%Project: AC-Lab by M.G. [created Feb 2020]
%Main Function: aclab_go
% ----------------------------------

    if cf2_on
        disp(strcat('(07) Avoidance        (ad2) [- ON -] = ',num2str(round(ad2_av(n_it),4)))) 
        disp(strcat('(08) Insensitivity    (cf2) [- ON -] = ',num2str(round(cf2_in(n_it),4))))
%     else
%         disp(strcat('(07) Avoidance        (ad2) [OFF] = ',   num2str(round(ad2_av(n_it),4)))) 
%         disp(strcat('(08) Insensitivity    (cf2) [OFF] = ',   num2str(round(cf2_in(n_it),4))))
    end
                
    if cf2_on
        disp(strcat('(09) x of P to need cf2     [- ON -] = ',num2str(round(p2need_cf2_x   (n_it),4)),...
                    '   m = ',                                num2str(round(p2need_cf2_x_m (n_it),4)),...
                    '   sd = ',                               num2str(round(p2need_cf2_x_sd(n_it),4))))
        disp(strcat('(10) x of P to give cf2     [- ON -] = ',num2str(round(p2give_cf2_x   (n_it),4)),...
                    '   m = ',                                num2str(round(p2give_cf2_x_m (n_it),4)),...
                    '   sd = ',                               num2str(round(p2give_cf2_x_sd(n_it),4))))
        disp(strcat('(11) x-fix of P to need cf2 [- ON -] = ',num2str(round(p2need_cf2_xf  (n_it),4))))
        disp(strcat('(12) x-fix of P to give cf2 [- ON -] = ',num2str(round(p2give_cf2_xf  (n_it),4))))
        disp(strcat('(13) P to need cf2          [- ON -] = ',num2str(round(p2need_cf2     (n_it),4)),...
                    '   m = ',                                num2str(round(p2need_cf2_m   (n_it),4)),...
                    '   sd = ',                               num2str(round(p2need_cf2_sd  (n_it),4))))
        disp(strcat('(14) P to give cf2          [- ON -] = ',num2str(round(p2give_cf2     (n_it),4)),...
                    '   m = ',                                num2str(round(p2give_cf2_m   (n_it),4)),...
                    '   sd = ',                               num2str(round(p2give_cf2_sd  (n_it),4))))
%     else
%         disp(strcat('(09) x of P to need cf2     [OFF] = ',num2str(round(p2need_cf2_x   (n_it),4)),...
%                     '   m = ',                             num2str(round(p2need_cf2_x_m (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2need_cf2_x_sd(n_it),4))))
%         disp(strcat('(10) x of P to give cf2     [OFF] = ',num2str(round(p2give_cf2_x   (n_it),4)),...
%                     '   m = ',                             num2str(round(p2give_cf2_x_m (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2give_cf2_x_sd(n_it),4))))
%         disp(strcat('(11) x-fix of P to need cf2 [OFF] = ',num2str(round(p2need_cf2_xf  (n_it),4))))
%         disp(strcat('(12) x-fix of P to give cf2 [OFF] = ',num2str(round(p2give_cf2_xf  (n_it),4))))
%         disp(strcat('(13) P to need cf2          [OFF] = ',num2str(round(p2need_cf2     (n_it),4)),...
%                     '   m = ',                             num2str(round(p2need_cf2_m   (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2need_cf2_sd  (n_it),4))))
%         disp(strcat('(14) P to give cf2          [OFF] = ',num2str(round(p2give_cf2     (n_it),4)),...
%                     '   m = ',                             num2str(round(p2give_cf2_m   (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2give_cf2_sd  (n_it),4))))
    end
            
    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
 
    if cf2_on
        disp(strcat('(15) CD need4     cf2 [- ON -] = ',num2str(need4_cf2    (n_it))))
        disp(strcat('(16) CR need2give cf2 [- ON -] = ',num2str(need2give_cf2(n_it))))
        disp(strcat('(17) n4 -> n2g    cf2 [- ON -] = ',num2str(n4_n2g_cf2   (n_it))))
        disp(strcat('(18) n2g -> n4    cf2 [- ON -] = ',num2str(n2g_n4_cf2   (n_it))))
        disp(strcat('(19) n4-n2g AST   cf2 [- ON -] = ',num2str(n4_n2g_st_cf2(n_it))))
        disp(strcat('(20) n4 -> No-n2g cf2 [- ON -] = ',num2str(n4_nn2g_cf2  (n_it))))
        disp(strcat('(21) n2g -> No-n4 cf2 [- ON -] = ',num2str(n2g_nn4_cf2  (n_it))))
%     else
%         disp(strcat('(15) CD need4     cf2 [OFF] = ',num2str(need4_cf2    (n_it))))
%         disp(strcat('(15) CR need2give cf2 [OFF] = ',num2str(need2give_cf2(n_it))))
%         disp(strcat('(17) n4 -> n2g    cf2 [OFF] = ',num2str(n4_n2g_cf2   (n_it))))
%         disp(strcat('(18) n2g -> n4    cf2 [OFF] = ',num2str(n2g_n4_cf2   (n_it))))
%         disp(strcat('(19) n4-n2g AST   cf2 [OFF] = ',num2str(n4_n2g_st_cf2(n_it))))
%         disp(strcat('(20) n4 -> No-n2g cf2 [OFF] = ',num2str(n4_nn2g_cf2  (n_it))))
%         disp(strcat('(21) n2g -> No-n4 cf2 [OFF] = ',num2str(n2g_nn4_cf2  (n_it))))
    end
    
    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
    
    if cf2_on
        disp(strcat('(22) Tot. CD need4      cf2 [- ON -] = ',num2str(round(need4_cf2_cntr    (n_it),4)),...
                    '   (',                                   num2str(round(need4_cf2_pc      (n_it),2)),'%)'))
        disp(strcat('(23) Tot. CR need2give  cf2 [- ON -] = ',num2str(round(need2give_cf2_cntr(n_it),4)),...
                    '   (',                                   num2str(round(need2give_cf2_pc  (n_it),2)),'%)'))
        disp(strcat('(24) Tot. n4 -> n2g     cf2 [- ON -] = ',num2str(round(n4_n2g_cf2_cntr   (n_it),4))))
        disp(strcat('(25) Tot. n2g -> n4     cf2 [- ON -] = ',num2str(round(n2g_n4_cf2_cntr   (n_it),4))))
        disp(strcat('(26) Tot. n4-n2g AST    cf2 [- ON -] = ',num2str(round(n4_n2g_st_cf2_cntr(n_it),4))))
        disp(strcat('(27) Tot. n4 -> No-n2g  cf2 [- ON -] = ',num2str(round(n4_nn2g_cf2_cntr  (n_it),4))))
        disp(strcat('(28) Tot. n2g -> No-n4  cf2 [- ON -] = ',num2str(round(n2g_nn4_cf2_cntr  (n_it),4))))
        disp(strcat('(29) Iterations with no cf2 [- ON -] = ',num2str(round(no_cf2_cntr       (n_it),4)),...
                    '   m = ',                                num2str(round(no_cf2_m          (n_it),4)),...
                    '   sd = ',                               num2str(round(no_cf2_sd         (n_it),4))))
%     else
%         disp(strcat('(22) Tot. CD needing    cf2 [OFF] = ',num2str(round(need4_cf2_cntr    (n_it),4)),...
%                     '   (',                                num2str(round(need4_cf2_pc      (n_it),2)),'%)'))
%         disp(strcat('(23) Tot. CR need2give  cf2 [OFF] = ',num2str(round(need2give_cf2_cntr(n_it),4)),...
%                     '   (',                                num2str(round(need2give_cf2_pc  (n_it),2)),'%)'))
%         disp(strcat('(24) Tot. n4 -> n2g     cf2 [OFF] = ',num2str(round(n4_n2g_cf2_cntr   (n_it),4))))
%         disp(strcat('(25) Tot. n2g -> n4     cf2 [OFF] = ',num2str(round(n2g_n4_cf2_cntr   (n_it),4))))
%         disp(strcat('(26) Tot. n4-n2g AST    cf2 [OFF] = ',num2str(round(n4_n2g_st_cf2_cntr(n_it),4))))
%         disp(strcat('(27) Tot. n4 -> No-n2g  cf2 [OFF] = ',num2str(round(n4_nn2g_cf2_cntr  (n_it),4))))
%         disp(strcat('(28) Tot. n2g -> No-n4  cf2 [OFF] = ',num2str(round(n2g_nn4_cf2_cntr  (n_it),4))))
%         disp(strcat('(29) Iterations with no cf2 [OFF] = ',num2str(round(no_cf2_cntr       (n_it),4)),...
%                     '   m = ',                             num2str(round(no_cf2_m          (n_it),4)),...
%                     '   sd = ',                            num2str(round(no_cf2_sd         (n_it),4))))
    end

    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
    
    if cf2_on
        disp(strcat('(30) CD e-distance (cf2)          [- ON -] = ',num2str(round(cf2_ed_cd     (n_it),4)),...
                    '   m = ',                                      num2str(round(cf2_ed_cd_m   (n_it),4)),...
                    '   sd = ',                                     num2str(round(cf2_ed_cd_sd  (n_it),4)),...
                    ' [',                                           num2str(round(cf2_ed_m2t_cd (n_it),4)),']'))
        disp(strcat('(31) CR e-distance (cf2)          [- ON -] = ',num2str(round(cf2_ed_cr     (n_it),4)),...
                    '   m = ',                                      num2str(round(cf2_ed_cr_m   (n_it),4)),...
                    '   sd = ',                                     num2str(round(cf2_ed_cr_sd  (n_it),4)),...
                    ' [',                                           num2str(round(cf2_ed_m2t_cr (n_it),4)),']'))
        disp(strcat('(32) CD target e-distance (cf2)   [- ON -] = ',num2str(round(cf2_ed_trgt_cd(n_it),4))))
        disp(strcat('(33) CR target e-distance (cf2)   [- ON -] = ',num2str(round(cf2_ed_trgt_cr(n_it),4))))
        disp(strcat('(34) CD indifference (cf2)        [- ON -] = ',num2str(round(cf2_i_cd      (n_it),4)),...
                    '   m = ',                                      num2str(round(cf2_i_cd_m    (n_it),4)),...
                    '   sd = ',                                     num2str(round(cf2_i_cd_sd   (n_it),4)),...
                    ' [',                                           num2str(round(cf2_i_m2t_cd  (n_it),4)),']'))   
        disp(strcat('(35) CR indifference (cf2)        [- ON -] = ',num2str(round(cf2_i_cr      (n_it),4)),...
                    '   m = ',                                      num2str(round(cf2_i_cr_m    (n_it),4)),...
                    '   sd = ',                                     num2str(round(cf2_i_cr_sd   (n_it),4)),...
                    ' [',                                           num2str(round(cf2_i_m2t_cr  (n_it),4)),']'))
        disp(strcat('(36) CD target indifference (cf2) [- ON -] = ',num2str(round(cf2_i_trgt_cd (n_it),4))))
        disp(strcat('(37) CR target indifference (cf2) [- ON -] = ',num2str(round(cf2_i_trgt_cr (n_it),4))))
        %disp(strcat('(38) CD i-fix (cf2)               [- ON -] = ',num2str(round(cf2_if_cd     (n_it),4))))
        %disp(strcat('(39) CR i-fix (cf2)               [- ON -] = ',num2str(round(cf2_if_cr     (n_it),4))))
        disp(strcat('(38) CD i-fix (cf2)               [- OFF -]'))
        disp(strcat('(39) CR i-fix (cf2)               [- OFF -]')) 
%     else
%         disp(strcat('(30) CD e-distance (cf2)          [OFF] = ',num2str(round(cf2_ed_cd     (n_it),4)),...
%                     '   m = ',                                   num2str(round(cf2_ed_cd_m   (n_it),4)),...
%                     '   sd = ',                                  num2str(round(cf2_ed_cd_sd  (n_it),4)),...
%                     ' [',                                        num2str(round(cf2_ed_m2t_cd (n_it),4)),']'))
%         disp(strcat('(31) CR e-distance (cf2)          [OFF] = ',num2str(round(cf2_ed_cr     (n_it),4)),...
%                     '   m = ',                                   num2str(round(cf2_ed_cr_m   (n_it),4)),...
%                     '   sd = ',                                  num2str(round(cf2_ed_cr_sd  (n_it),4)),...
%                     ' [',                                        num2str(round(cf2_ed_m2t_cr (n_it),4)),']'))
%         disp(strcat('(32) CD target e-distance (cf2)   [OFF] = ',num2str(round(cf2_ed_trgt_cd(n_it),4))))
%         disp(strcat('(33) CR target e-distance (cf2)   [OFF] = ',num2str(round(cf2_ed_trgt_cr(n_it),4))))
%         disp(strcat('(34) CD indifference (cf2)        [OFF] = ',num2str(round(cf2_i_cd      (n_it),4)),...
%                     '   m = ',                                   num2str(round(cf2_i_cd_m    (n_it),4)),...
%                     '   sd = ',                                  num2str(round(cf2_i_cd_sd   (n_it),4)),...
%                     ' [',                                        num2str(round(cf2_i_m2t_cd  (n_it),4)),']'))   
%         disp(strcat('(35) CR indifference (cf2)        [OFF] = ',num2str(round(cf2_i_cr      (n_it),4)),...
%                     '   m = ',                                   num2str(round(cf2_i_cr_m    (n_it),4)),...
%                     '   sd = ',                                  num2str(round(cf2_i_cr_sd   (n_it),4)),...
%                     ' [',                                        num2str(round(cf2_i_m2t_cr  (n_it),4)),']'))
%         disp(strcat('(36) CD target indifference (cf2) [OFF] = ',num2str(round(cf2_i_trgt_cd (n_it),4))))
%         disp(strcat('(37) CR target indifference (cf2) [OFF] = ',num2str(round(cf2_i_trgt_cr (n_it),4))))
%         disp(strcat('(38) CD i-fix (cf2)               [OFF] = ',num2str(round(cf2_if_cd     (n_it),4))))
%         disp(strcat('(39) CR i-fix (cf2)               [OFF] = ',num2str(round(cf2_if_cr     (n_it),4)))) 
    end
    
    disp(strcat('---------------------------------------------------'))
    
