%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% --- cf3 plot_stats print on screen ------------------------------------------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ----------------------------------
%Project: AC-Lab by M.G. [created Feb 2020]
%Main Function: aclab_go
% ----------------------------------

    if cf3_on
        disp(strcat('(07) Ambivalence      (ad3) [- ON -] = ',num2str(round(ad3_am(n_it),4)))) 
        disp(strcat('(08) Unresponsiveness (cf3) [- ON -] = ',num2str(round(cf3_un(n_it),4))))
%     else
%         disp(strcat('(07) Ambivalence      (ad3) [OFF] = ',   num2str(round(ad3_am(n_it),4)))) 
%         disp(strcat('(08) Unresponsiveness (cf3) [OFF] = ',   num2str(round(cf3_un(n_it),4))))
    end
    
    if cf3_on         
        disp(strcat('(09) x of P to need cf3     [- ON -] = ',num2str(round(p2need_cf3_x   (n_it),4)),...
                    '   m = ',                                num2str(round(p2need_cf3_x_m (n_it),4)),...
                    '   sd = ',                               num2str(round(p2need_cf3_x_sd(n_it),4))))
        disp(strcat('(10) x of P to give cf3     [- ON -] = ',num2str(round(p2give_cf3_x   (n_it),4)),...
                    '   m = ',                                num2str(round(p2give_cf3_x_m (n_it),4)),...
                    '   sd = ',                               num2str(round(p2give_cf3_x_sd(n_it),4))))  
        disp(strcat('(11) x-fix of P to need cf3 [- ON -] = ',num2str(round(p2need_cf3_xf  (n_it),4))))
        disp(strcat('(12) x-fix of P to give cf3 [- ON -] = ',num2str(round(p2give_cf3_xf  (n_it),4))))
        disp(strcat('(13) P to need cf3          [- ON -] = ',num2str(round(p2need_cf3     (n_it),4)),...
                    '   m = ',                                num2str(round(p2need_cf3_m   (n_it),4)),...
                    '   sd = ',                               num2str(round(p2need_cf3_sd  (n_it),4))))
        disp(strcat('(14) P to give cf3          [- ON -] = ',num2str(round(p2give_cf3     (n_it),4)),...
                    '   m = ',                                num2str(round(p2give_cf3_m   (n_it),4)),...
                    '   sd = ',                               num2str(round(p2give_cf3_sd  (n_it),4))))
%     else
%         disp(strcat('(09) x of P to need cf3     [OFF] = ',num2str(round(p2need_cf3_x   (n_it),4)),...
%                     '   m = ',                             num2str(round(p2need_cf3_x_m (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2need_cf3_x_sd(n_it),4))))
%         disp(strcat('(10) x of P to give cf3     [OFF] = ',num2str(round(p2give_cf3_x   (n_it),4)),...
%                     '   m = ',                             num2str(round(p2give_cf3_x_m (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2give_cf3_x_sd(n_it),4))))
%         disp(strcat('(11) x-fix of P to need cf3 [OFF] = ',num2str(round(p2need_cf3_xf  (n_it),4))))
%         disp(strcat('(12) x-fix of P to give cf3 [OFF] = ',num2str(round(p2give_cf3_xf  (n_it),4))))
%         disp(strcat('(13) P to need cf3          [OFF] = ',num2str(round(p2need_cf3     (n_it),4)),...
%                     '   m = ',                             num2str(round(p2need_cf3_m   (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2need_cf3_sd  (n_it),4))))
%         disp(strcat('(14) P to give cf3          [OFF] = ',num2str(round(p2give_cf3     (n_it),4)),...
%                     '   m = ',                             num2str(round(p2give_cf3_m   (n_it),4)),...
%                     '   sd = ',                            num2str(round(p2give_cf3_sd  (n_it),4))))
    end
            
    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
    
    if cf3_on
        disp(strcat('(15) CD need4     cf3 [- ON -] = ',num2str(need4_cf3    (n_it))))
        disp(strcat('(16) CR need2give cf3 [- ON -] = ',num2str(need2give_cf3(n_it))))
        disp(strcat('(17) n4 -> n2g    cf3 [- ON -] = ',num2str(n4_n2g_cf3   (n_it))))
        disp(strcat('(18) n2g -> n4    cf3 [- ON -] = ',num2str(n2g_n4_cf3   (n_it))))
        disp(strcat('(19) n4-n2g AST   cf3 [- ON -] = ',num2str(n4_n2g_st_cf3(n_it)))) 
        disp(strcat('(20) n4 -> No-n2g cf3 [- ON -] = ',num2str(n4_nn2g_cf3  (n_it))))
        disp(strcat('(21) n2g -> No-n4 cf3 [- ON -] = ',num2str(n2g_nn4_cf3  (n_it))))
%     else
%         disp(strcat('(15) CD need4     cf3 [OFF] = ',num2str(need4_cf3    (n_it))))
%         disp(strcat('(16) CR need2give cf3 [OFF] = ',num2str(need2give_cf3(n_it))))
%         disp(strcat('(17) n4 -> n2g    cf3 [OFF] = ',num2str(n4_n2g_cf3   (n_it))))
%         disp(strcat('(18) n2g -> n4    cf3 [OFF] = ',num2str(n2g_n4_cf3   (n_it))))
%         disp(strcat('(19) n4-n2g AST   cf3 [OFF] = ',num2str(n4_n2g_st_cf3(n_it)))) 
%         disp(strcat('(20) n4 -> No-n2g cf3 [OFF] = ',num2str(n4_nn2g_cf3  (n_it))))
%         disp(strcat('(21) n2g -> No-n4 cf3 [OFF] = ',num2str(n2g_nn4_cf3  (n_it))))
    end
    
    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
    
    if cf3_on
        disp(strcat('(22) Tot. CD need4      cf3 [- ON -] = ',num2str(round(need4_cf3_cntr    (n_it),4)),...
                    '   (',                                   num2str(round(need4_cf3_pc      (n_it),2)),'%)'))
        disp(strcat('(23) Tot. CR need2give  cf3 [- ON -] = ',num2str(round(need2give_cf3_cntr(n_it),4)),...
                    '   (',                                   num2str(round(need2give_cf3_pc  (n_it),2)),'%)'))
        disp(strcat('(24) Tot. n4 -> n2g     cf3 [- ON -] = ',num2str(round(n4_n2g_cf3_cntr   (n_it),4))))
        disp(strcat('(25) Tot. n2g -> n4     cf3 [- ON -] = ',num2str(round(n2g_n4_cf3_cntr   (n_it),4))))
        disp(strcat('(26) Tot. n4-n2g AST    cf3 [- ON -] = ',num2str(round(n4_n2g_st_cf3_cntr(n_it),4))))
        disp(strcat('(27) Tot. n4 -> No-n2g  cf3 [- ON -] = ',num2str(round(n4_nn2g_cf3_cntr  (n_it),4))))
        disp(strcat('(28) Tot. n2g -> No-n4  cf3 [- ON -] = ',num2str(round(n2g_nn4_cf3_cntr  (n_it),4))))
        disp(strcat('(29) Iterations with no cf3 [- ON -] = ',num2str(round(no_cf3_cntr       (n_it),4)),...
                    '   m = ',                                num2str(round(no_cf3_m          (n_it),4)),...
                    '   sd = ',                               num2str(round(no_cf3_sd         (n_it),4))))
%     else 
%         disp(strcat('(22) Tot. CD need4      cf3 [OFF] = ',num2str(round(need4_cf3_cntr    (n_it),4)),...
%                     '   (',                                num2str(round(need4_cf3_pc      (n_it),2)),'%)'))
%         disp(strcat('(23) Tot. CR need2give  cf3 [OFF] = ',num2str(round(need2give_cf3_cntr(n_it),4)),...
%                     '   (',                                num2str(round(need2give_cf3_pc  (n_it),2)),'%)'))
%         disp(strcat('(24) Tot. n4 -> n2g     cf3 [OFF] = ',num2str(round(n4_n2g_cf3_cntr   (n_it),4))))
%         disp(strcat('(25) Tot. n2g -> n4     cf3 [OFF] = ',num2str(round(n2g_n4_cf3_cntr   (n_it),4))))
%         disp(strcat('(26) Tot. n4-n2g AST    cf3 [OFF] = ',num2str(round(n4_n2g_st_cf3_cntr(n_it),4))))
%         disp(strcat('(27) Tot. n4 -> No-n2g  cf3 [OFF] = ',num2str(round(n4_nn2g_cf3_cntr  (n_it),4))))
%         disp(strcat('(28) Tot. n2g -> No-n4  cf3 [OFF] = ',num2str(round(n2g_nn4_cf3_cntr  (n_it),4))))
%         disp(strcat('(29) Iterations with no cf3 [OFF] = ',num2str(round(no_cf3_cntr       (n_it),4)),...
%                     '   m = ',                             num2str(round(no_cf3_m          (n_it),4)),...
%                     '   sd = ',                            num2str(round(no_cf3_sd         (n_it),4))))
    end 
    
    disp(strcat('---   ---   ---   ---   ---   ---   ---   ---   ---'))
    
    if cf3_on  
        disp(strcat('(30) CD p-distance (cf3)        [- ON -] = ',num2str(round(cf3_pd_cd     (n_it),4)),...
                    '   m = ',                                    num2str(round(cf3_pd_cd_m   (n_it),4)),...
                    '   sd = ',                                   num2str(round(cf3_pd_cd_sd  (n_it),4)),...
                    ' [',                                         num2str(round(cf3_pd_m2t_cd (n_it),4)),']'))
        disp(strcat('(31) CR p-distance (cf3)        [- ON -] = ',num2str(round(cf3_pd_cr     (n_it),4)),...
                    '   m = ',                                    num2str(round(cf3_pd_cr_m   (n_it),4)),...
                    '   sd = ',                                   num2str(round(cf3_pd_cr_sd  (n_it),4)),...
                    ' [',                                         num2str(round(cf3_pd_m2t_cr (n_it),4)),']'))
        disp(strcat('(32) CD target p-distance (cf3) [- ON -] = ',num2str(round(cf3_pd_trgt_cd(n_it),4)))) 
        disp(strcat('(33) CR target p-distance (cf3) [- ON -] = ',num2str(round(cf3_pd_trgt_cr(n_it),4))))
        disp(strcat('(34) CD distancing (cf3)        [- ON -] = ',num2str(round(cf3_d_cd      (n_it),4)),...
                    '   m = ',                                    num2str(round(cf3_d_cd_m    (n_it),4)),...
                    '   sd = ',                                   num2str(round(cf3_d_cd_sd   (n_it),4)),...
                    ' [',                                         num2str(round(cf3_d_m2t_cd  (n_it),4)),']'))
        disp(strcat('(35) CR distancing (cf3)        [- ON -] = ',num2str(round(cf3_d_cr      (n_it),4)),...
                    '   m = ',                                    num2str(round(cf3_d_cr_m    (n_it),4)),...
                    '   sd = ',                                   num2str(round(cf3_d_cr_sd   (n_it),4)),...
                    ' [',                                         num2str(round(cf3_d_m2t_cr  (n_it),4)),']'))
        disp(strcat('(36) CD target distancing (cf3) [- ON -] = ',num2str(round(cf3_d_trgt_cd (n_it),4))))        
        disp(strcat('(37) CR target distancing (cf3) [- ON -] = ',num2str(round(cf3_d_trgt_cr (n_it),4))))        
        %disp(strcat('(38) CD d-fix (cf3)             [- ON -] = ',num2str(round(cf3_df_cd     (n_it),4))))        
        %disp(strcat('(39) CR d-fix (cf3)             [- ON -] = ',num2str(round(cf3_df_cr     (n_it),4))))
        disp(strcat('(38) CD d-fix (cf3)             [- OFF -]'))        
        disp(strcat('(39) CR d-fix (cf3)             [- OFF -]'))
%     else
%         disp(strcat('(30) CD p-distance (cf3)        [OFF] = ',num2str(round(cf3_pd_cd     (n_it),4)),...
%                     '   m = ',                                 num2str(round(cf3_pd_cd_m   (n_it),4)),...
%                     '   sd = ',                                num2str(round(cf3_pd_cd_sd  (n_it),4)),...
%                     ' [',                                      num2str(round(cf3_pd_m2t_cd (n_it),4)),']'))
%         disp(strcat('(31) CR p-distance (cf3)        [OFF] = ',num2str(round(cf3_pd_cr     (n_it),4)),...
%                     '   m = ',                                 num2str(round(cf3_pd_cr_m   (n_it),4)),...
%                     '   sd = ',                                num2str(round(cf3_pd_cr_sd  (n_it),4)),...
%                     ' [',                                      num2str(round(cf3_pd_m2t_cr (n_it),4)),']'))
%         disp(strcat('(32) CD target p-distance (cf3) [OFF] = ',num2str(round(cf3_pd_trgt_cd(n_it),4)))) 
%         disp(strcat('(33) CR target p-distance (cf3) [OFF] = ',num2str(round(cf3_pd_trgt_cr(n_it),4))))
%         disp(strcat('(34) CD distancing (cf3)        [OFF] = ',num2str(round(cf3_d_cd      (n_it),4)),...
%                     '   m = ',                                 num2str(round(cf3_d_cd_m    (n_it),4)),...
%                     '   sd = ',                                num2str(round(cf3_d_cd_sd   (n_it),4)),...
%                     ' [',                                      num2str(round(cf3_d_m2t_cd  (n_it),4)),']'))
%         disp(strcat('(35) CR distancing (cf3)        [OFF] = ',num2str(round(cf3_d_cr      (n_it),4)),...
%                     '   m = ',                                 num2str(round(cf3_d_cr_m    (n_it),4)),...
%                     '   sd = ',                                num2str(round(cf3_d_cr_sd   (n_it),4)),...
%                     ' [',                                      num2str(round(cf3_d_m2t_cr  (n_it),4)),']'))
%         disp(strcat('(36) CD target distancing (cf3) [OFF] = ',num2str(round(cf3_d_trgt_cd (n_it),4))))        
%         disp(strcat('(37) CR target distancing (cf3) [OFF] = ',num2str(round(cf3_d_trgt_cr (n_it),4))))        
%         disp(strcat('(38) CD d-fix (cf3)             [OFF] = ',num2str(round(cf3_df_cd     (n_it),4))))        
%         disp(strcat('(39) CR d-fix (cf3)             [OFF] = ',num2str(round(cf3_df_cr     (n_it),4))))
    end
    
    disp(strcat('---------------------------------------------------'))
    
